kind: pipeline
type: docker
name: default

steps:
- name: trigger-e2e-firecracker-aws
  image: arwineap/docker-alpine-toolbox:latest
  environment:
    E2E_TRIGGER_TOKEN:
      from_secret: e2e_trigger_token_firecracker
  when:
    event: [ push, pull_request ]
    status: success
  commands:
    - id=$(curl -X POST -F "token=$${E2E_TRIGGER_TOKEN}" -F "ref=master" -F "variables[DOTSCIENCE_TF_CLOUD_PROVIDER]=aws" -F "variables[DOTSCIENCE_TF_COMMIT_HASH]=$${DRONE_COMMIT}" https://gitlab.dotmesh.com/api/v4/projects/dotmesh%2Fe2e-firecracker-sync/trigger/pipeline | jq .id)
    - echo "Triggered successfully, pipeline - https://gitlab.dotmesh.com/dotmesh/e2e-firecracker-sync/pipelines/$${id}"
